### PR TITLE
Accordion expand/collapse feature.

### PR DESCRIPTION
**Pull request by thefex**
Implements issue #60

### CODE REVIEW

**Comment by thefex** [comment]
Sorry for merging master - not feature branch but I have to add now one more feature/improvement (scroll to expanded/collapsed row) using the current code base.

**Comment by thefex** [comment]
Added auto-scroll to selected expanded/collapsed row. This code can be merged now.

**Comment by martijn00** [comment]
The namespace `ExpandableInternal` sounds a bit weird. Why not just call it `Expandable`?

**Comment by thefex** [comment]
Right - that was weird. Fixed

**Comment by martijn00** [comment]
Are you sure this doesn't break anything? Quite a lot of code changed in here.

**Comment by thefex** [comment]
That should not break anything. Expand logic was refactored, the default, old behaviour is kept. With my PR you can set IsAccordionEnabled (or something like that) which makes that only one item will be expanded at same time. Plus UI is scrolled to the item on expand. The other PR I've made adds support for detecting which and when item is expanded/collapsed which is useful sometimes (for ex. Items count on Header title). I use that code in one application developed for company I work for.

**Pull request merged**
