### PR TITLE
Add support to configure menu icon

### LINKED ISSUE #32: Allow user to use own hamburger icon
https://github.com/MvvmCross/MvvmCross-iOSSupport/blob/master/MvvmCross.iOS.Support.XamarinSidebar/Hints/MvxSidebarActivePanelPresentationHint.cs#L49

This needs to be configurable

### PR DESCRIPTION
**Pull request by mvanbeusekom**
This pull request allows the user to use a custom image for the menu button. This is accomplished by implementing the MenuButtonImage property from the IMvxSidebarMenu interface. This PR closes #32

Examples are provided in the existing "MvvmCross.iOS.Support.Sidebar" project (implementation can be found in the "RightPanelView.cs" file).

### CODE REVIEW

**Comment by martijn00** [comment]
Looks good, but we should add support for this in the other presenter too.

**Comment by mvanbeusekom** [comment]
I agree and I was looking for the please where the JAPanel solution adds an icon but I cannot find it. Almost looks like the JAPanel provides it's own icon. I will investigate a but more thorough

**Comment by mvanbeusekom** [comment]
Did some more research and confirmed that the JASidePanelController indeed paints and sets the image by itself using a static 'defaultImage' method. The way I understand it is that the image gets set by the JASidePanelController each time it decides it needs to show the menu button (e.g. when on iPhone and only centre panel is showing). Since the 'defaultImage' method is static and defined inside the class it cannot be overridden from the outside, making it (to my knowledge) impossible to set a custom image.

So my conclusion would be that it is only possible to use custom icons when using the XamarinSidebar component and unfortunately not available when using JASidePanels.

**Comment by Cheesebaron** [comment]
Just to link the issue and PR together: #32

**Comment by mvanbeusekom** [comment]
Guess it doesn't hurt to link it twice, I already linked it in original PR description ;)

**Comment by Cheesebaron** [comment]
Ah, didn't see it :D Hard to spot a # and a number :P

**Comment by martijn00** [comment]
Thanks!

**Pull request merged**
