### PR TITLE
Load sidebarmenu only once

### LINKED ISSUE #40: "Hamburger" icon disappears
Can be reproduced in current MvvmCross-iOSSupport.Samples (commit c56c97f).
### Steps to reproduce
1. Run MvvmCross-iOSSupport.Samples with MvvmCross.iOS.Support.Sidebar as startup project
2. Tap on Hamburger icon, notice that sidebar opens and Hamburger icon remains visible
3. Tap on **Example Menu Item** in sidebar, notice that Hamburger icon disappears
### Expected behavior

Hamburger icon should always be visible
### Actual behavior

Hamburger icon disappears after tapping on first menu element
### Configuration

**Version:** 4.2.3

**Platform:** iOS

NOTE: calling ShowMenu for every newly-opened screen does make the Hamburger icon reappear, but it isn't a viable solution because it creates a new instance of the menu

### PR DESCRIPTION
**Pull request by mvanbeusekom**
This will solve the problem where the sidebar view (and matching ViewModel) are constructed for each page that should be able to show a sidebar menu. 

You can now configure the menu(s) that should be shown in advance (see the Samples/SideMenuSample/MvvmCross.iOS.Support.Core/AppStart.cs for sample configuration). If necessary it is still possible to override the menu for a specific page.

This PR closes #40.

### CODE REVIEW

**Comment by martijn00** [comment]
Looks good! I think we should Move the Sidepanels to a separate sample folder so it won't break the JaSidePanels.

**Comment by mvanbeusekom** [comment]
@martijn00 I made a second commit splitting the JASidePanels and XamarinSidebar example projects into their own folders.

**Comment by ghost** [comment]
@mvanbeusekom  @martijn00 I upgraded one of my solutions from 4.2 to 4.4 and now the sidebar has icons on both the left and right side - and I can't figure out how to turn off the side bar on the right side.  Ideas on removing this behavior so that you can only have one side bar and choose which side it's on?

**Comment by mvanbeusekom** [comment]
@biozal unfortunately during the last Mvx release a bug was introduced in the implementation of the XamarinSidebar support, resulting in the behavior you describe. This mistake has been corrected and wil be released with the next version of MvvmCross. 

For now you have the following options:
1. Downgrade to MvvmCross 4.3.0
2. Wait for the next release (I don't know when this will be)
3. Get the latest version of the XamarinSidebar and compile it yourself (you'll only need the XamarinSidebar implementation, which is fully compatible with the current 4.4.0 version of MvvmCross)

I sincerely apologize for this inconvenience.

**Comment by artmon** [comment]
I did downgrade to 4.3.0 mvvmcross framework, but right menu still is left if pulling the edge

**Pull request merged**
