### PR TITLE
MvxTabsPresenter

### PR DESCRIPTION
**Pull request by nmilcoff**
I have added a new presenter based on Tabs! I'm using it on production environment so I can say it is reliable (some points can be improved, for sure).

I have added a complete sample as well, showing the capabilities and the way to use the presenter. I will also write a blog post to explain a bit more how to use it.

Last but not least, I have also added the .gitattributes file used in other MvvmCross repos.

Please tell me if there are any problems with line endigs, I've done the steps recommended in the release notes of Mvx 4.2.3 (before cloning the repo).

### CODE REVIEW

**Comment by Cheesebaron** [comment]
Could you please put the sample in the sample folder?

**Comment by modplug** [comment]
Great work ;)

**Comment by nmilcoff** [comment]
@modplug thanks! :)

@Cheesebaron Not sure if I understand you correctly... I've created a solution folder called "TabsSample" and renamed the "Sample" folder to "SideMenuSample":

sshot

Should I reorder the folders other way?

**Comment by Cheesebaron** [comment]
If you look in the physical folder of the project.

**Comment by nmilcoff** [comment]
Done :)

**Comment by Cheesebaron** [comment]
Thanks 💋

**Comment by modplug** [comment]
@Cheesebaron getting jiggy with it... :speak_no_evil:

**Comment by nmilcoff** [comment]
Did you guys have time to review this PR? :) Should I merge master into it?

**Comment by Cheesebaron** [comment]
Will have a looksie tomorrow if no one else wants to. Please do merge master in.

**Comment by nmilcoff** [comment]
I've merged master again, please tell me if there's something that should be changed

**Comment by Cheesebaron** [comment]
This one looks good, except for sample defaults to use one of your provisioning profiles for some reason. So had to change the Debug|iPhoneSimulator section to

```
<DebugSymbols>true</DebugSymbols>
    <DebugType>full</DebugType>
    <Optimize>false</Optimize>
    <OutputPath>bin\iPhoneSimulator\Debug</OutputPath>
    <DefineConstants>DEBUG</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
    <ConsolePause>false</ConsolePause>
    <MtouchArch>i386</MtouchArch>
    <MtouchLink>None</MtouchLink>
    <MtouchDebug>true</MtouchDebug>
```

Instead of what it was to have it run

**Pull request merged**
